#web:

login-service:
  image: cub/login-service
  container_name: loginservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
  links:
   - customer-service:customerservice
   - mongodb-loginservice:mongoserver
  ports:
   # forward the service port through the vm to the host
   - "9000:8080"
  environment:
   SPRING_PROFILES_ACTIVE: remote
   # tell spring boot where to find mongodb (if started with profile "local")
   SPRING_DATA_MONGODB_HOST: mongoserver

customer-service:
  image: cub/customer-service
  container_name: customerservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
  links:
   - mongodb-customerservice:mongoserver
  ports:
   # forward the service port through the vm to the host
   - "9100:8080"
  environment:
   # tell spring boot where to find mongodb
   SPRING_DATA_MONGODB_HOST: mongoserver

article-service:
  image: cub/article-service
  container_name: articleservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
  links:
   - mongodb-articleservice:mongoserver
  ports:
   # forward the service port through the vm to the host
   - "9200:8080"
  environment:
   # tell spring boot where to find mongodb
   SPRING_DATA_MONGODB_HOST: mongoserver

mongodb-customerservice:
  image: mongo
  container_name: mongo-customerservice
  volumes_from:
   - datavolumes
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   - /var/cub-code-walkthrough/mongo/customer/data/db:/data/db
  ports:
   # forward the mongo port through the vm to the host
   - "27017:27017"

mongodb-loginservice:
  image: mongo
  container_name: mongo-loginservice
  volumes_from:
   - datavolumes
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   - /var/cub-code-walkthrough/mongo/login/data/db:/data/db
  ports:
   # forward the mongo port through the vm to the host
   - "27117:27017"

mongodb-articleservice:
  image: mongo
  container_name: mongo-articleservice
  volumes_from:
   - datavolumes
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   - /var/cub-code-walkthrough/mongo/article/data/db:/data/db
  ports:
   # forward the mongo port through the vm to the host
   - "27217:27017"

nginx:
  image: cub/nginx
  container_name: nginx
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   # find a better solution for this one
   - $HOME/dockermounts/cub-code-walkthrough/nginx/html:/etc/nginx/html
  links:
   - login-service:loginservice
   - customer-service:customerservice
   - article-service:articleservice
  ports:
   # forward the nginx port through the vm to the host
   - "10080:80"

eventstore:
  image: cub/eventstore
  volumes:
     # mount the host's /dev/urandom to speed up creating the secret
     - /dev/urandom:/dev/random
     - /Volumes/Development/__docker_volumes/eventstore_data/cub-codewalkthrough/data/db:/var/eventstore/db
     - /Volumes/Development/__docker_volumes/eventstore_data/cub-codewalkthrough/data/log:/var/eventstore/log
  ports:
   - "1113:1113"
   - "2113:2113"
  environment:
   EVENTSTORE_DB: /var/eventstore/db
   EVENTSTORE_LOG: /var/eventstore/log

datavolumes:
  image: cub/volumes
