#web:

login-service:
  image: cub/login-service
  container_name: loginservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
  links:
   - customer-service:customerservice
   - mongodb-loginservice:mongoserver
  ports:
   # forward the service port through the vm to the host
   - "9000:8080"
   - "11005:5005"
  environment:
   SPRING_PROFILES_ACTIVE: remote
   # tell spring boot where to find mongodb (if started with profile "local")
   SPRING_DATA_MONGODB_HOST: mongoserver
   ES_SERVER: 192.168.99.100
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

customer-service:
  image: cub/customer-service
  container_name: customerservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
  links:
   - mongodb-customerservice:mongoserver
  ports:
   # forward the service port through the vm to the host
   - "9100:8080"
   - "11105:5005"
  environment:
   # tell spring boot where to find mongodb
   SPRING_DATA_MONGODB_HOST: mongoserver
   ES_SERVER: 192.168.99.100
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

article-service:
  image: cub/article-service
  container_name: articleservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
  links:
   - mongodb-articleservice:mongoserver
  ports:
   # forward the service port through the vm to the host
   - "9200:8080"
   - "11205:5005"
  environment:
   # tell spring boot where to find mongodb
   SPRING_DATA_MONGODB_HOST: mongoserver
   ES_SERVER: 192.168.99.100
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

cart-service:
  image: cub/cart-service
  container_name: cartservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
  links:
   - mongodb-cartservice:mongoserver
  ports:
   # forward the service port through the vm to the host
   - "9300:8080"
   - "11305:5005"
  environment:
   # tell spring boot where to find mongodb
   SPRING_DATA_MONGODB_HOST: mongoserver
   ES_SERVER: 192.168.99.100
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

mongodb-customerservice:
  image: mongo
  container_name: mongo-customerservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   - /Volumes/Development/__docker_volumes/mongo_data/cub-codewalkthrough/customer/data/db:/data/db
  ports:
   # forward the mongo port through the vm to the host
   - "27017:27017"
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

mongodb-loginservice:
  image: mongo
  container_name: mongo-loginservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   - /Volumes/Development/__docker_volumes/mongo_data/cub-codewalkthrough/login/data/db:/data/db
  ports:
   # forward the mongo port through the vm to the host
   - "27117:27017"
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

mongodb-articleservice:
  image: mongo
  container_name: mongo-articleservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   - /Volumes/Development/__docker_volumes/mongo_data/cub-codewalkthrough/article/data/db:/data/db
  ports:
   # forward the mongo port through the vm to the host
   - "27217:27017"
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

mongodb-cartservice:
  image: mongo
  container_name: mongo-cartservice
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   - /Volumes/Development/__docker_volumes/mongo_data/cub-codewalkthrough/mongo/data/db:/data/db
  ports:
   # forward the mongo port through the vm to the host
   - "27317:27017"
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

nginx:
  image: cub/nginx
  container_name: nginx
  volumes:
   # mount the host's /dev/urandom to speed up creating the secret
   - /dev/urandom:/dev/random
   # find a better solution for this one
   - $HOME/dockermounts/cub-code-walkthrough/nginx/html:/etc/nginx/html
  links:
   - login-service:loginservice
   - customer-service:customerservice
   - article-service:articleservice
   - cart-service:cartservice
  ports:
   # forward the nginx port through the vm to the host
   - "10080:80"
  log_driver: "gelf"
  log_opt:
    tag: "{{.Name}}"
    gelf-address: "udp://192.168.99.100:12201"

