FROM adbrowne/eventstore
MAINTAINER Ralph Winzinger <ralph@winzinger-online.de>

RUN mkdir -p /var/eventstore/db
RUN mkdir -p /var/eventstore/log

ENV EVENTSTORE_DB /var/eventstore/db
ENV EVENTSTORE_LOG /var/eventstore/log